Repository fond-of-impala/fond-of-impala, pull requests merged in 2023-10, with the labels that each got.

#120 🐛Bugfix: map only available data
  bundles/customer-anonymizer-company-user-connector/src/FondOfImpala/Zed/CustomerAnonymizerCompanyUserConnector/Persistence/Propel/Mapper/CompanyUserMapper.php
  dandelion.json
Labels: bug

#125 ✨ Initialize `company-cart-search-rest-api`-bundle
  bundles/company-cart-search-rest-api/.github/workflows/main.yml
  bundles/company-cart-search-rest-api/LICENSE
  bundles/company-cart-search-rest-api/Makefile
  bundles/company-cart-search-rest-api/codeception.yml
  bundles/company-cart-search-rest-api/composer.json
  bundles/company-cart-search-rest-api/phpstan.neon
  bundles/company-cart-search-rest-api/src/FondOfImpala/Shared/CompanyCartSearchRestApi/CompanyCartSearchRestApiConstants.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/CompanyCartSearchRestApiFacadeInterface.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Expander/QueryJoinCollectionExpanderInterface.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Filter/CompanyUuidFilterInterface.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Filter/IdCustomerFilterInterface.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Reader/CompanyReaderInterface.php
  bundles/company-cart-search-rest-api/tests/_bootstrap.php
  bundles/company-cart-search-rest-api/tests/_data/.gitkeep
  bundles/company-cart-search-rest-api/tests/_output/.gitignore
  bundles/company-cart-search-rest-api/tests/_support/.gitkeep
  codeception.yml
  composer.json
Labels: enhancement

#127 ✨ Make not allowed filter field types configurable
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/CustomerSearchQuoteQueryExpanderPlugin.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/CompanyCartSearchRestApiConfig.php
  bundles/company-cart-search-rest-api/tests/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/CustomerSearchQuoteQueryExpanderPluginTest.php
Labels: enhancement

#128 ✨ Add only mine filter to cart search endpoint
  bundles/company-cart-search-rest-api/src/FondOfImpala/Glue/CompanyCartSearchRestApi/Plugin/CartSearchRestApiExtension/OnlyMineFilterFieldsExpanderPlugin.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Shared/CompanyCartSearchRestApi/CompanyCartSearchRestApiConstants.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/OnlyMineSearchQuoteQueryExpanderPlugin.php
  bundles/company-cart-search-rest-api/tests/FondOfImpala/Glue/CompanyCartSearchRestApi/Plugin/CartSearchRestApiExtension/OnlyMineFilterFieldsExpanderPluginTest.php
  bundles/company-cart-search-rest-api/tests/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/OnlyMineSearchQuoteQueryExpanderPluginTest.php
Labels: enhancement

#124 ✨ Integrate pr size labeler in ci pipeline
  .github/workflows/main.yml
Labels: enhancement, size/m

#133 🧹add cu stuff
  bundles/company-users-rest-api-price-list-connector/.github/workflows/main.yml
Labels: enhancement, size/s

#129 ✨ Initialize `permission-cart-search-rest-api`-bundle
  bundles/permission-cart-search-rest-api/.github/workflows/main.yml
  bundles/permission-cart-search-rest-api/LICENSE
  bundles/permission-cart-search-rest-api/Makefile
  bundles/permission-cart-search-rest-api/codeception.yml
  bundles/permission-cart-search-rest-api/composer.json
  bundles/permission-cart-search-rest-api/phpstan.neon
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Shared/PermissionCartSearchRestApi/Transfer/permission_cart_search_rest_api.transfer.xml
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/Persistence/PermissionCartSearchRestApiRepositoryInterface.php
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/Persistence/Propel/Schema/spy_company_user.schema.xml
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/Persistence/Propel/Schema/spy_quote.schema.xml
  bundles/permission-cart-search-rest-api/tests/_bootstrap.php
  bundles/permission-cart-search-rest-api/tests/_data/.gitkeep
  bundles/permission-cart-search-rest-api/tests/_output/.gitignore
  bundles/permission-cart-search-rest-api/tests/_support/.gitkeep
  codeception.yml
  composer.json
Labels: enhancement, size/m

#130 ✨ Implement `permission-cart-search-rest-api`-bundle
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/PermissionSearchQuoteQueryExpanderPlugin.php
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/Communication/Plugin/PermissionExtension/SearchCartPermissionPlugin.php
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/PermissionCartSearchRestApiDependencyProvider.php
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/Persistence/PermissionCartSearchRestApiPersistenceFactory.php
  bundles/permission-cart-search-rest-api/src/FondOfImpala/Zed/PermissionCartSearchRestApi/Persistence/PermissionCartSearchRestApiRepository.php
  bundles/permission-cart-search-rest-api/tests/FondOfImpala/Zed/PermissionCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/PermissionSearchQuoteQueryExpanderPluginTest.php
  bundles/permission-cart-search-rest-api/tests/FondOfImpala/Zed/PermissionCartSearchRestApi/Communication/Plugin/PermissionExtension/SearchCartPermissionPluginTest.php
Labels: enhancement, size/m

#131 ✨ Remove cart search permission plugin from `company-cart-search-rest-api`-bundle
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/CustomerSearchQuoteQueryExpanderPlugin.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/PermissionExtension/SearchCartPermissionPlugin.php
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Persistence/CompanyCartSearchRestApiRepository.php
  bundles/company-cart-search-rest-api/tests/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/CustomerSearchQuoteQueryExpanderPluginTest.php
  bundles/company-cart-search-rest-api/tests/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/PermissionExtension/SearchCartPermissionPluginTest.php
Labels: enhancement, size/m

#134 🐛 'false' must be false
  bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/OnlyMineSearchQuoteQueryExpanderPlugin.php
Labels: bug, size/xs

#135 🐛 Use correct dependencies
  bundles/company-cart-search-rest-api/composer.json
  bundles/permission-cart-search-rest-api/composer.json
Labels: bug, size/xs

#136 ✨ Release new bundles
  composer.json
  dandelion.json
Labels: enhancement, size/s

#137 🐛 Allow company-user in version 2.0.0 also
  bundles/company-cart-search-rest-api/composer.json
  bundles/permission-cart-search-rest-api/composer.json
Labels: bug, size/xs

#138 ✨Implement `only-claimed` filter for `cart-search` rest api
  bundles/collaborative-cart-search-rest-api/LICENSE
  bundles/collaborative-cart-search-rest-api/Makefile
  bundles/collaborative-cart-search-rest-api/codeception.yml
  bundles/collaborative-cart-search-rest-api/composer.json
  bundles/collaborative-cart-search-rest-api/phpstan.neon
  bundles/collaborative-cart-search-rest-api/src/FondOfImpala/Glue/CollaborativeCartSearchRestApi/Plugin/CartSearchRestApiExtension/OnlyClaimedFilterFieldsExpanderPlugin.php
  bundles/collaborative-cart-search-rest-api/src/FondOfImpala/Shared/CollaborativeCartSearchRestApi/CollaborativeCartSearchRestApiConstants.php
  bundles/collaborative-cart-search-rest-api/src/FondOfImpala/Zed/CollaborativeCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/OnlyClaimedSearchQuoteQueryExpanderPlugin.php
  bundles/collaborative-cart-search-rest-api/tests/FondOfImpala/Glue/CollaborativeCartSearchRestApi/Plugin/CartSearchRestApiExtension/OnlyClaimedFilterFieldsExpanderPluginTest.php
  bundles/collaborative-cart-search-rest-api/tests/FondOfImpala/Zed/CollaborativeCartSearchRestApi/Communication/Plugin/CartSearchRestApiExtension/OnlyClaimedSearchQuoteQueryExpanderPluginTest.php
  bundles/collaborative-cart-search-rest-api/tests/_bootstrap.php
  bundles/collaborative-cart-search-rest-api/tests/_data/.gitkeep
  bundles/collaborative-cart-search-rest-api/tests/_output/.gitignore
  bundles/collaborative-cart-search-rest-api/tests/_support/.gitkeep
  codeception.yml
  composer.json
Labels: enhancement, size/l

#139 🔖release `collaborative-cart-search-rest-api` bundle
  dandelion.json
Labels: enhancement, size/xs
