Repository fond-of-impala/fond-of-impala, pull requests merged in 2023-12, with the labels that each got.

#153 🧹 Decrease qty in periods
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorBusinessFactory.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacade.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Expander/ItemExpander.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Expander/ItemExpanderInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Expander/QuoteExpander.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Expander/QuoteExpanderInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Filter/ConditionalAvailabilityPeriodsFilter.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Filter/ConditionalAvailabilityPeriodsFilterInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinder.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinderInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Generator/DeliveryDateGenerator.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Generator/DeliveryDateGeneratorInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Generator/MessageGenerator.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Generator/MessageGeneratorInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Model/ConditionalAvailabilityExpander.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reducer/ConditionalAvailabilityPeriodsReducer.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reducer/ConditionalAvailabilityPeriodsReducerInterface.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorBusinessFactoryTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacadeTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Expander/ItemExpanderTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Expander/QuoteExpanderTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Filter/ConditionalAvailabilityPeriodsFilterTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinderTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Generator/DeliveryDateGeneratorTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Generator/MessageGeneratorTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Model/ConditionalAvailabilityExpanderTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reducer/ConditionalAvailabilityPeriodsReducerTest.php
Labels: enhancement, size/xl

#154 ✨ Add facade method to retrieve unavailable skus by quote
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorBusinessFactory.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacade.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacadeInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Filter/ConditionalAvailabilityPeriodsFilter.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Filter/ConditionalAvailabilityPeriodsFilterInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinder.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinderInterface.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReader.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReaderInterface.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorBusinessFactoryTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacadeTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReaderTest.php
Labels: enhancement, size/m

#155 🧹 Remove duplicate logic
  bundles/conditional-availability-checkout-connector/composer.json
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Shared/ConditionalAvailabilityCheckoutConnector/ConditionalAvailabilityCheckoutConnectorConstants.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Shared/ConditionalAvailabilityCheckoutConnector/Transfer/conditional_availability_checkout_connector.transfer.xml
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Checker/AvailabilitiesChecker.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Checker/AvailabilitiesCheckerInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/ConditionalAvailabilityCheckoutConnectorBusinessFactory.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/ConditionalAvailabilityCheckoutConnectorFacade.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/ConditionalAvailabilityCheckoutConnectorFacadeInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Grouper/ItemsGrouper.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Grouper/ItemsGrouperInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Mapper/ConditionalAvailabilityCriteriaFilterMapper.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Mapper/ConditionalAvailabilityCriteriaFilterMapperInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Reader/CustomerReader.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Reader/CustomerReaderInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Communication/ConditionalAvailabilityCheckoutConnectorCommunicationFactory.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Communication/Plugin/CheckoutExtension/ConditionalAvailabilityCheckoutPreConditionPlugin.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/ConditionalAvailabilityCheckoutConnectorDependencyProvider.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityCartConnectorFacadeBridge.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityCartConnectorFacadeInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityFacadeBridge.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityFacadeInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToCustomerFacadeBridge.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToCustomerFacadeInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Service/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityServiceBridge.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Service/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityServiceInterface.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Persistence/ConditionalAvailabilityCheckoutConnectorPersistenceFactory.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Persistence/ConditionalAvailabilityCheckoutConnectorRepository.php
  bundles/conditional-availability-checkout-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Persistence/ConditionalAvailabilityCheckoutConnectorRepositoryInterface.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Checker/AvailabilitiesCheckerTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/ConditionalAvailabilityCheckoutConnectorBusinessFactoryTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/ConditionalAvailabilityCheckoutConnectorFacadeTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Grouper/ItemsGrouperTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Mapper/ConditionalAvailabilityCriteriaFilterMapperTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Business/Reader/CustomerReaderTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Communication/Plugin/CheckoutExtension/ConditionalAvailabilityCheckoutPreConditionPluginTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityFacadeBridgeTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Facade/ConditionalAvailabilityCheckoutConnectorToCustomerFacadeBridgeTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Dependency/Service/ConditionalAvailabilityCheckoutConnectorToConditionalAvailabilityServiceBridgeTest.php
  dandelion.json
Labels: size/l

#157 🐛 Add caching for splittable-(checkout/quote)
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinder.php
  bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReader.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReaderTest.php
Labels: bug, size/s

#160 ✨ Add unique key to conditional availability period
  bundles/conditional-availability/src/FondOfImpala/Shared/ConditionalAvailability/Transfer/contional_availability.transfer.xml
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityBusinessFactory.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/Generator/KeyGenerator.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/Generator/KeyGeneratorInterface.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/Model/ConditionalAvailabilityPeriodsPersister.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/Propel/Schema/foi_conditional_availability.schema.xml
  bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/Generator/KeyGeneratorTest.php
  bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/Model/ConditionalAvailabilityPeriodsPersisterTest.php
  dandelion.json
Labels: enhancement, size/s

#161 ✨ Use `EventBehaviorFacade` to publish conditional availability periods
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/Plugin/Event/Listener/ProductListProductConcreteListener.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/ProductListConditionalAvailabilityPageSearchCommunicationFactory.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToConditionalAvailabilityPageSearchFacadeBridge.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToConditionalAvailabilityPageSearchFacadeInterface.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToEventBehaviorFacadeBridge.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToEventBehaviorFacadeInterface.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/ProductListConditionalAvailabilityPageSearchDependencyProvider.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/ProductListConditionalAvailabilityPageSearchCommunicationFactoryTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToConditionalAvailabilityPageSearchFacadeBridgeTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToEventBehaviorFacadeBridgeTest.php
  dandelion.json
Labels: enhancement, size/m

#162 🐛 Fix typo in unit test
  bundles/product-list-conditional-availability-page-search/codeception.yml
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/ProductListConditionalAvailabilityPageSearchBusinessFactoryTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/ProductListConditionalAvailabilityPageSearchCommunicationFactoryTest.php
Labels: size/xs

#163 ✨ Make db field `key` required and unique
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/Propel/Schema/foi_conditional_availability.schema.xml
  dandelion.json
Labels: size/xs

#164 ✨ Use `key` as `conditionalAvailabilityPeriodKey`
  bundles/conditional-availability-bulk-api/composer.json
  bundles/conditional-availability-cart-connector/composer.json
  bundles/conditional-availability-page-search-rest-api/composer.json
  bundles/conditional-availability-page-search/composer.json
  bundles/conditional-availability-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityPageSearch/Schema/conditional-availability-period.json
  bundles/conditional-availability-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityPageSearch/Transfer/conditional_availability_page_search.transfer.xml
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchBusinessFactory.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacade.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacadeInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Filter/IdConditionalAvailabilityFilter.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Filter/IdConditionalAvailabilityFilterInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Filter/KeyFilter.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Filter/KeyFilterInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchDataMapper.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchExpander.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchPublisher.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchPublisherInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchUnpublisher.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchUnpublisherInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/ConditionalAvailabilityPageSearchCommunicationFactory.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Console/ConditionalAvailabilityPageSearchPublishConsole.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Event/ConditionalAvailabilityEventResourceQueryContainerPlugin.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Event/ConditionalAvailabilityPeriodEventResourceQueryContainerPlugin.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Event/Listener/ConditionalAvailabilityPageSearchListener.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Event/Listener/ConditionalAvailabilityPeriodPageSearchListener.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Event/Subscriber/ConditionalAvailabilityPageSearchEventSubscriber.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/SynchronizationExtension/ConditionalAvailabilityPeriodSynchronizationDataBulkRepositoryPlugin.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchDependencyProvider.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToEventBehaviorFacadeBridge.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToEventBehaviorFacadeInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToStoreFacadeBridge.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToStoreFacadeInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/ConditionalAvailabilityPageSearchEntityManager.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/ConditionalAvailabilityPageSearchEntityManagerInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/ConditionalAvailabilityPageSearchPersistenceFactory.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/ConditionalAvailabilityPageSearchQueryContainer.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/ConditionalAvailabilityPageSearchQueryContainerInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/ConditionalAvailabilityPageSearchRepository.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/Propel/Mapper/ConditionalAvailabilityPeriodPageSearchMapper.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/Propel/Mapper/ConditionalAvailabilityPeriodPageSearchMapperInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/Propel/Schema/fos_conditional_availability_page_search.schema.xml
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchBusinessFactoryTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacadeTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Filter/IdConditionalAvailabilityFilterTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Filter/KeyFilterTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchDataMapperTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchExpanderTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/ConditionalAvailabilityPageSearchCommunicationFactoryTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Event/Subscriber/ConditionalAvailabilityPageSearchEventSubscriberTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToEventBehaviorFacadeBridgeTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToStoreFacadeBridgeTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Service/ConditionalAvailabilityPageSearchToUtilEncodingServiceBridgeTest.php
  bundles/conditional-availability-product-page-search/composer.json
  bundles/product-list-conditional-availability-page-search/composer.json
  dandelion.json
Labels: enhancement, size/xl

#165 🐛 Extend pk by `conditional_availability_period_key`
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Persistence/Propel/Schema/fos_conditional_availability_page_search.schema.xml
  dandelion.json
Labels: bug, size/xs

#166 🐛 Use * for empty image set name
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPlugin.php
  bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPluginTest.php
  dandelion.json
Labels: bug

#168 ✨ Publish abstract and concrete products async
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactory.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Trigger/StockStatusTrigger.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchDependencyProvider.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToEventBehaviorFacadeBridge.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToEventBehaviorFacadeInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToProductPageSearchFacadeBridge.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToProductPageSearchFacadeInterface.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchDependencyProviderTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Plugin/SearchExtension/StockStatusQueryExpanderPluginTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactoryTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Generator/StockStatusGeneratorTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Reader/ProductAbstractReaderTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Trigger/StockStatusTriggerTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/DataExpander/StockStatusDataLoadExpanderPluginTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/DataLoader/StockStatusDataLoaderPluginTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToEventBehaviorFacadeBridgeTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToProductPageSearchFacadeBridgeTest.php
  dandelion.json
Labels: enhancement, size/m

#169 🐛 Swap if and else case for fallback group key
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPlugin.php
  bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPluginTest.php
  dandelion.json
Labels: bug, size/xs

#170 ✨ Use publisher for conditional availability
  bundles/conditional-availability-page-search/composer.json
  bundles/conditional-availability-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchConstants.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodDeletePublisherPlugin.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodWritePublisherPlugin.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodDeletePublisherPluginTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodWritePublisherPluginTest.php
  composer.json
  dandelion.json
Labels: enhancement, size/s

#172 🧹 migrate latest performance optimisation
  bundles/company-type-role/Makefile
  bundles/company-type-role/src/FondOfImpala/Shared/CompanyTypeRole/Transfer/company_type_role.transfer.xml
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Builder/CompanyRoleCriteriaFilterBuilder.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Builder/CompanyRoleCriteriaFilterBuilderInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/CompanyTypeRoleBusinessFactory.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Filter/CompanyTypeNameFilter.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Filter/CompanyTypeNameFilterInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Mapper/PermissionKeyMapper.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Mapper/PermissionKeyMapperInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/CompanyRoleReader.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/CompanyRoleReaderInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/PermissionReader.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/PermissionReaderInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Synchronizer/PermissionSynchronizer.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/CompanyTypeRoleConfig.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/CompanyTypeRoleDependencyProvider.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Dependency/Facade/CompanyTypeRoleToPropelFacadeBridge.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Dependency/Facade/CompanyTypeRoleToPropelFacadeInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRolePersistenceFactory.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepository.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepositoryInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/CompanyMapper.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/CompanyMapperInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/CompanyRoleMapper.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/CompanyRoleMapperInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/PermissionMapper.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/PermissionMapperInterface.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Builder/CompanyRoleCriteriaFilterBuilderTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/CompanyTypeRoleBusinessFactoryTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Filter/CompanyTypeNameFilterTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Mapper/PermissionKeyMapperTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Model/CompanyRoleAssignerTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/CompanyRoleReaderTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/PermissionReaderTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Synchronizer/PermissionSynchronizerTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/CompanyTypeRoleDependencyProviderTest.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Dependency/Facade/CompanyTypeRoleToPropelFacadeBridgeTest.php
Labels: enhancement, size/l

#177 🧹 company users bulk rest api
  bundles/company-users-bulk-rest-api/src/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyBusinessUnitToCompanyTransferExpander.php
  bundles/company-users-bulk-rest-api/src/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyRolesToCompanyTransferExpander.php
  bundles/company-users-bulk-rest-api/src/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Manager/BulkManager.php
  bundles/company-users-bulk-rest-api/tests/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyBusinessUnitToCompanyTransferExpanderTest.php
  bundles/company-users-bulk-rest-api/tests/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyRolesToCompanyTransferExpanderTest.php
  bundles/company-users-bulk-rest-api/tests/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Manager/BulkManagerTest.php
  dandelion.json
Labels: enhancement, size/s

#179 🧹 update Makefiles
  bundles/company-company-type-gui/Makefile
  bundles/company-type-converter-extension/Makefile
  bundles/company-type-converter/Makefile
  bundles/company-type-data-import/Makefile
  bundles/company-type-role/Makefile
  bundles/company-type/Makefile
  bundles/company-user-company-assigner/Makefile
Labels: enhancement, size/m

#184 🧹 Add phpcs fixes
  bundles/company-users-rest-api/src/FondOfImpala/Zed/CompanyUsersRestApi/Persistence/Expander/CompanyUserQueryExpander.php
  bundles/customer-price-product-price-list-page-search/src/FondOfImpala/Client/CustomerPriceProductPriceListPageSearch/Plugin/SearchExtension/CustomerPriceListQueryExpanderPlugin.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Client/ProductListPriceProductPriceListPageSearch/Plugin/SearchExtension/ProductListPriceProductPriceListPageSearchQueryExpanderPlugin.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Communication/Plugin/Event/Listener/ProductListPriceProductAbstractPriceListPageSearchListener.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Communication/Plugin/Event/Listener/ProductListPriceProductConcretePriceListPageSearchListener.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToEventBehaviorFacadeBridge.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToEventBehaviorFacadeInterface.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToPriceProductPriceListPageSearchFacadeBridge.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToPriceProductPriceListPageSearchFacadeInterface.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToProductFacadeBridge.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToProductFacadeInterface.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToProductListFacadeBridge.php
  bundles/product-list-price-product-price-list-page-search/src/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToProductListFacadeInterface.php
  bundles/product-list-price-product-price-list-page-search/tests/FondOfImpala/Client/ProductListPriceProductPriceListPageSearch/Plugin/SearchExtension/ProductListPriceProductPriceListPageSearchQueryExpanderPluginTest.php
  bundles/product-list-price-product-price-list-page-search/tests/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Business/Model/PriceProductAbstractPriceListPageSearchExpanderTest.php
  bundles/product-list-price-product-price-list-page-search/tests/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Business/Model/PriceProductConcretePriceListPageSearchExpanderTest.php
  bundles/product-list-price-product-price-list-page-search/tests/FondOfImpala/Zed/ProductListPriceProductPriceListPageSearch/Dependency/Facade/ProductListPriceProductPriceListPageSearchToEventBehaviorFacadeBridgeTest.php
Labels: enhancement, size/s

#183 ✨ Use publisher system for price product price list
  bundles/price-product-price-list-page-search/composer.json
  bundles/price-product-price-list-page-search/src/FondOfImpala/Client/PriceProductPriceListPageSearch/Dependency/Client/PriceProductPriceListPageSearchToSearchClientBridge.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Client/PriceProductPriceListPageSearch/Dependency/Client/PriceProductPriceListPageSearchToSearchClientInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchDependencyProvider.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchFactory.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/AbstractPriceProductSearchMapper.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/AbstractPriceProductSearchWriter.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchExpander.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchMapper.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchWriter.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchWriterInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchExpander.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchMapper.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchWriter.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchWriterInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/PriceProductPriceListPageSearchBusinessFactory.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/PriceProductPriceListPageSearchFacade.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/PriceProductPriceListPageSearchFacadeInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Console/PriceProductPriceListPageSearchPublishConsole.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/Listener/PriceProductPriceListAbstractDeleteListener.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/Listener/PriceProductPriceListAbstractListener.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/Listener/PriceProductPriceListConcreteDeleteListener.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/Listener/PriceProductPriceListConcreteListener.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/PriceProductAbstractPriceListPageSearchEventResourceQueryContainerPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/PriceProductConcretePriceListPageSearchEventResourceQueryContainerPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductAbstractPriceListDeletePublisherPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductAbstractPriceListWritePublisherPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductConcretePriceListDeletePublisherPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductConcretePriceListWritePublisherPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Synchronization/PriceProductAbstractPriceListPageSynchronizationDataPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Synchronization/PriceProductConcretePriceListPageSynchronizationDataPlugin.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Dependency/Facade/PriceProductPriceListPageSearchToEventBehaviorFacadeBridge.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Dependency/Facade/PriceProductPriceListPageSearchToEventBehaviorFacadeInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/PriceProductPriceListPageSearchEntityManager.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/PriceProductPriceListPageSearchEntityManagerInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/PriceProductPriceListPageSearchRepository.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/PriceProductPriceListPageSearchRepositoryInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/Propel/Mapper/PriceProductPriceListPageSearchMapper.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/Propel/Mapper/PriceProductPriceListPageSearchMapperInterface.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/Propel/Schema/foi_price_product_price_list_page_search.schema.xml
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchDependencyProvider.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchExpanderTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchMapperTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchExpanderTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchMapperTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductAbstractPriceListDeletePublisherPluginTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductAbstractPriceListWritePublisherPluginTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductConcretePriceListDeletePublisherPluginTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/PublisherExtension/PriceProductConcretePriceListWritePublisherPluginTest.php
Labels: enhancement, size/l

#186 🧹 Add rector fixes for `price-product-price-list-page-search`
  bundles/price-product-price-list-page-search/src/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchConfig.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchDependencyProvider.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchFactory.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceGrouper.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchWriter.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchWriter.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/Subscriber/PriceProductPriceListPageSearchEventSubscriber.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchConfig.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchDependencyProvider.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/Dependency/Client/PriceProductPriceListPageSearchToSearchClientBridgeTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/Plugin/SearchExtension/PriceProductAbstractPriceListSearchQueryPluginTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/Plugin/SearchExtension/PriceProductConcretePriceListSearchQueryPluginTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/Plugin/SearchExtension/RawPriceProductAbstractPriceListResultFormatterPluginTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/Plugin/SearchExtension/RawPriceProductConcretePriceListResultFormatterPluginTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchClientTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchDependencyProviderTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Client/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchFactoryTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceGrouperTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchExpanderTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductAbstractSearchMapperTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchExpanderTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/Model/PriceProductConcreteSearchMapperTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/PriceProductPriceListPageSearchBusinessFactoryTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Business/PriceProductPriceListPageSearchFacadeTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/Plugin/Event/Subscriber/PriceProductPriceListPageSearchEventSubscriberTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Communication/PriceProductPriceListPageSearchCommunicationFactoryTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Dependency/Facade/PriceProductPriceListPageSearchToEventBehaviorFacadeBridgeTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Dependency/Facade/PriceProductPriceListPageSearchToStoreFacadeBridgeTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Dependency/Service/PriceProductPriceListPageSearchToUtilEncodingServiceBridgeTest.php
  bundles/price-product-price-list-page-search/tests/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/Prope/Mapper/PriceProductPriceListPageSearchMapperTest.php
Labels: size/m

#185 ✨ Release price list bundles
  dandelion.json
Labels: enhancement, size/s

#188 🧹 Add constants for publish queues
  bundles/price-product-price-list-page-search/src/FondOfImpala/Shared/PriceProductPriceListPageSearch/PriceProductPriceListPageSearchConstants.php
  bundles/price-product-price-list-page-search/src/FondOfImpala/Zed/PriceProductPriceListPageSearch/Persistence/Propel/Schema/foi_price_product_price_list_page_search.schema.xml
  bundles/price-product-price-list/src/FondOfImpala/Zed/PriceProductPriceList/Dependency/PriceProductPriceListEvents.php
Labels: enhancement, size/s

#187 🧹 Add more rule sets (dead code, early return, ...) to rector config
  rector.php
Labels: enhancement, size/s
