Repository fond-of-impala/fond-of-impala, pull requests merged in 2023-11, with the labels that each got.

#143 🔖 release add default image group name if `image set` name is missing
  dandelion.json
Labels: bug

#144 ✨add `stock-status` values in the `valueFacets` aggregation
  .github/workflows/main.yml
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchDependencyProvider.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchFactory.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Dependency/Client/ConditionalAvailabilityProductPageSearchToCustomerClientBridge.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Dependency/Client/ConditionalAvailabilityProductPageSearchToCustomerClientInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Plugin/SearchExtension/StockStatusQueryExpanderPlugin.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Plugin/SearchExtension/StockStatusResultFormatterPlugin.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchDependencyProviderTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchFactoryTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Dependency/Client/ConditionalAvailabilityProductPageSearchToCustomerClientBridgeTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Plugin/SearchExtension/StockStatusQueryExpanderPluginTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Plugin/SearchExtension/StockStatusResultFormatterPluginTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearchFactoryTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/Plugin/SearchExtension/StockStatusQueryExpanderPluginTest.php
Labels: enhancement, size/m

#145 🔖 update version for `conditional-availability-product-page-search`
  dandelion.json
Labels: enhancement, size/xs

#147 🐛 Check timestamps of all periods
  bundles/conditional-availability-product-page-search/.github/workflows/main.yml
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactory.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchFacade.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Exception/InvalidRawValueException.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductConcretePageSearchExpander.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductConcretePageSearchExpanderInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductPageLoadExpander.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductPageLoadExpanderInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Generator/StockStatusGenerator.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Generator/StockStatusGeneratorInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ProductPage/ProductPageDataExpander.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ProductPage/ProductPageDataExpanderInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Reader/ProductAbstractReader.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactoryTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchFacadeTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductPageLoadExpanderTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Generator/StockStatusGeneratorTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ProductPage/ProductPageDataExpanderTest.php
Labels: bug, size/l

#149 ✨ Trigger expired `stock-status`
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactory.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchFacade.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchFacadeInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Trigger/StockStatusTrigger.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Trigger/StockStatusTriggerInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Console/TriggerStockStatusConsole.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchDependencyProvider.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Persistence/ConditionalAvailabilityProductPageSearchPersistenceFactory.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Persistence/ConditionalAvailabilityProductPageSearchRepository.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Persistence/ConditionalAvailabilityProductPageSearchRepositoryInterface.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactoryTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchFacadeTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Trigger/StockStatusTriggerTest.php
Labels: dependencies, size/m

#150 🔖 release `stock-status` trigger
  dandelion.json
Labels: enhancement
