Repository fond-of-impala/fond-of-impala, pull requests merged in 2024-05, with the labels that each got.

#258 Bugfix: fix schema
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/Propel/Mapper/WebUiSettingsMapper.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/Propel/Mapper/WebUiSettingsMapperInterface.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/WebUiSettingsCustomerConnectorPersistenceFactory.php
  bundles/web-ui-settings/src/FondOfImpala/Zed/WebUiSettings/Persistence/Propel/Mapper/WebUiSettingsMapper.php
  bundles/web-ui-settings/src/FondOfImpala/Zed/WebUiSettings/Persistence/Propel/Mapper/WebUiSettingsMapperInterface.php
  bundles/web-ui-settings/src/FondOfImpala/Zed/WebUiSettings/Persistence/Propel/Schema/foi_web_ui_settings.schema.xml
  bundles/web-ui-settings/src/FondOfImpala/Zed/WebUiSettings/Persistence/WebUiSettingsEntityManager.php
  bundles/web-ui-settings/src/FondOfImpala/Zed/WebUiSettings/Persistence/WebUiSettingsPersistenceFactory.php
Labels: bug, size/s

#259 Chore/company type role sync performance
  bundles/company-type-role/src/FondOfImpala/Shared/CompanyTypeRole/CompanyTypeRoleConstants.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/CompanyTypeRoleBusinessFactory.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Synchronizer/CompanyRoleSynchronizer.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/CompanyTypeRoleConfig.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/CompanyTypeRoleDependencyProvider.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Dependency/Facade/CompanyTypeRoleToCompanyFacadeBridge.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Dependency/Facade/CompanyTypeRoleToCompanyFacadeInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRolePersistenceFactory.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepository.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepositoryInterface.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Synchronizer/CompanyRoleSynchronizerTest.php
  dandelion.json
Labels: enhancement, size/m

#261 fix: handle `false` as param value correctly
  bundles/conditional-availability-page-search/src/FondOfImpala/Client/ConditionalAvailabilityPageSearch/Plugin/SearchExtension/OnePerSkuConditionalAvailabilityPageSearchQueryExpanderPlugin.php
  bundles/product-group-hash/src/FondOfImpala/Client/ProductGroupHash/Plugin/SearchExtension/OnePerGroupHashQueryExpanderPlugin.php
  dandelion.json
Labels: bug, size/xs

#260 feat: add stock-status in `search-result-data`
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Plugin/EnhancedCatalogExtension/StockStatusProductExpanderPlugin.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchConstants.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityProductPageSearch/Transfer/conditional_availability_product_page_search.transfer.xml
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/Elasticsearch/StockStatusMapExpanderPlugin.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityProductPageSearch/Plugin/EnhancedCatalogExtension/StockStatusProductExpanderPluginTest.php
  dandelion.json
Labels: size/s
