Repository fond-of-impala/fond-of-impala, pull requests merged in 2024-04, with the labels that each got.

#249 add more roles to company type roles
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/CompanyTypeRoleConfig.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/CompanyTypeRoleConfigTest.php
  dandelion.json
Labels: enhancement, size/s

#252 feature: allow to add a fallback group hash
  bundles/product-group-hash/src/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Listener/ProductGroupHashListener.php
  bundles/product-group-hash/tests/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Listener/ProductGroupHashListenerTest.php
  dandelion.json
Labels: enhancement, size/s

#254 add web UI settings customer connector
  bundles/web-ui-settings-customer-connector/.github/workflows/main.yml
  bundles/web-ui-settings-customer-connector/.gitignore
  bundles/web-ui-settings-customer-connector/LICENSE
  bundles/web-ui-settings-customer-connector/Makefile
  bundles/web-ui-settings-customer-connector/codeception.yml
  bundles/web-ui-settings-customer-connector/composer.json
  bundles/web-ui-settings-customer-connector/phpstan.neon
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Shared/WebUiSettingsCustomerConnector/Transfer/web_ui_settings_customer_connector.transfer.xml
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Shared/WebUiSettingsCustomerConnector/WebUiSettingsCustomerConnectorConstants.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Business/Manager/WebUiSettingsManager.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Business/Manager/WebUiSettingsManagerInterface.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Business/WebUiSettingsCustomerConnectorBusinessFactory.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Business/WebUiSettingsCustomerConnectorFacade.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Business/WebUiSettingsCustomerConnectorFacadeInterface.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Communication/Plugin/Customer/WebUiSettingsCustomerPreUpdatePlugin.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Communication/Plugin/Customer/WebUiSettingsCustomerTransferExpanderPlugin.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Dependency/Facade/WebUiSettingsCustomerConnectorToWebUiSettingsFacadeBridge.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Dependency/Facade/WebUiSettingsCustomerConnectorToWebUiSettingsFacadeInterface.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/Propel/Mapper/WebUiSettingsMapper.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/Propel/Mapper/WebUiSettingsMapperInterface.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/Propel/Schema/spy_customer.schema.xml
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/WebUiSettingsCustomerConnectorPersistenceFactory.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/WebUiSettingsCustomerConnectorRepository.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/Persistence/WebUiSettingsCustomerConnectorRepositoryInterface.php
  bundles/web-ui-settings-customer-connector/src/FondOfImpala/Zed/WebUiSettingsCustomerConnector/WebUiSettingsCustomerConnectorDependencyProvider.php
  bundles/web-ui-settings-customer-connector/tests/FondOfImpala/Zed/WebUiSettings/Business/Manager/WebUiSettingsManagerTest.php
  bundles/web-ui-settings-customer-connector/tests/FondOfImpala/Zed/WebUiSettings/Communication/Plugin/Customer/WebUiSettingsCustomerPreUpdatePluginTest.php
  bundles/web-ui-settings-customer-connector/tests/FondOfImpala/Zed/WebUiSettings/Communication/Plugin/Customer/WebUiSettingsCustomerTransferExpanderPluginTest.php
  bundles/web-ui-settings-customer-connector/tests/_bootstrap.php
  bundles/web-ui-settings-customer-connector/tests/_data/.gitkeep
  bundles/web-ui-settings-customer-connector/tests/_output/.gitignore
  bundles/web-ui-settings-customer-connector/tests/_support/.gitkeep
Labels: enhancement, size/l

#255 add web-ui-settings-quote-connector bundle
  bundles/web-ui-settings-quote-connector/.github/workflows/main.yml
  bundles/web-ui-settings-quote-connector/.gitignore
  bundles/web-ui-settings-quote-connector/LICENSE
  bundles/web-ui-settings-quote-connector/Makefile
  bundles/web-ui-settings-quote-connector/codeception.yml
  bundles/web-ui-settings-quote-connector/composer.json
  bundles/web-ui-settings-quote-connector/phpstan.neon
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Shared/WebUiSettingsQuoteConnector/Transfer/web_ui_settings_quote_connector.transfer.xml
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Shared/WebUiSettingsQuoteConnector/WebUiSettingsQuoteConnectorConstants.php
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Zed/WebUiSettingsQuoteConnector/Business/Expander/QuoteExpander.php
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Zed/WebUiSettingsQuoteConnector/Business/Expander/QuoteExpanderInterface.php
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Zed/WebUiSettingsQuoteConnector/Business/WebUiSettingsQuoteConnectorBusinessFactory.php
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Zed/WebUiSettingsQuoteConnector/Business/WebUiSettingsQuoteConnectorFacade.php
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Zed/WebUiSettingsQuoteConnector/Business/WebUiSettingsQuoteConnectorFacadeInterface.php
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Zed/WebUiSettingsQuoteConnector/Communication/Plugin/QuoteExtension/CartViewQuoteExpanderPlugin.php
  bundles/web-ui-settings-quote-connector/src/FondOfImpala/Zed/WebUiSettingsQuoteConnector/WebUiSettingsQuoteConnectorConfig.php
  bundles/web-ui-settings-quote-connector/tests/FondOfImpala/Zed/WebUiSettings/Business/Expander/QuoteExpanderTest.php
  bundles/web-ui-settings-quote-connector/tests/FondOfImpala/Zed/WebUiSettings/Communication/Plugin/QuoteExtension/CartViewQuoteExpanderPluginTest.php
  bundles/web-ui-settings-quote-connector/tests/_bootstrap.php
  bundles/web-ui-settings-quote-connector/tests/_data/.gitkeep
  bundles/web-ui-settings-quote-connector/tests/_output/.gitignore
  bundles/web-ui-settings-quote-connector/tests/_support/.gitkeep
Labels: enhancement, size/m

#256 fix standalon run
  bundles/web-ui-settings-quote-connector/composer.json
Labels: dependencies, size/s

#257 introduce company user search company typ bundle
  bundles/company-user-search-company-type/.github/workflows/main.yml
  bundles/company-user-search-company-type/LICENSE
  bundles/company-user-search-company-type/Makefile
  bundles/company-user-search-company-type/codeception.yml
  bundles/company-user-search-company-type/composer.json
  bundles/company-user-search-company-type/phpstan.neon
  bundles/company-user-search-company-type/src/FondOfImpala/Shared/CompanyUserSearchCompanyType/Transfer/company_user_search_company_type.transfer.xml
  bundles/company-user-search-company-type/src/FondOfImpala/Zed/CompanyUserSearchCompanyType/Communication/Dependency/Plugin/CompanyUserSearchRestApi/CompanyUserTransferCompanyTypePostMapExpanderPlugin.php
  bundles/company-user-search-company-type/src/FondOfImpala/Zed/CompanyUserSearchCompanyType/CompanyUserSearchCompanyTypeDependencyProvider.php
  bundles/company-user-search-company-type/src/FondOfImpala/Zed/CompanyUserSearchCompanyType/Persistence/CompanyUserSearchCompanyTypePersistenceFactory.php
  bundles/company-user-search-company-type/src/FondOfImpala/Zed/CompanyUserSearchCompanyType/Persistence/CompanyUserSearchCompanyTypeRepository.php
  bundles/company-user-search-company-type/src/FondOfImpala/Zed/CompanyUserSearchCompanyType/Persistence/CompanyUserSearchCompanyTypeRepositoryInterface.php
  bundles/company-user-search-company-type/tests/_bootstrap.php
  bundles/company-user-search-company-type/tests/_data/.gitkeep
  bundles/company-user-search-company-type/tests/_output/.gitignore
  bundles/company-user-search-company-type/tests/_support/.gitkeep
  composer.json
  dandelion.json
Labels: enhancement, size/m
