Repository fond-of-impala/fond-of-impala, pull requests merged in 2024-11, with the labels that each got.

#285 Feature: calculate erp order cancellation (item) amounts
  bundles/erp-order-cancellation-rest-api/composer.json
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiFacade.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiFacadeInterface.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/ErpOrderCancellationRestApiCommunicationFactory.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PostSave/RecalculateTotalAmountErpOrderCancellationPostSavePlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PreSave/CancellationCalculationsErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiEntityManager.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiEntityManagerInterface.php
  composer.json
Labels: enhancement, size/m

#286 Bugfix: fix permission sync if no permission set was set before
  bundles/company-type-role/composer.json
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/CompanyRoleReader.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Reader/CompanyRoleReaderInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Synchronizer/PermissionSynchronizer.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepository.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepositoryInterface.php
  dandelion.json
Labels: bug, size/m

#287 chore: erp order cacellation map customer
  bundles/erp-order-cancellation-rest-api/composer.json
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/Transfer/erp_order_cancellation_rest_api.transfer.xml
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/Propel/Mapper/EntityToTransferMapper.php
  bundles/erp-order-cancellation/composer.json
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Mapper/EntityToTransferMapper.php
Labels: enhancement, size/s

#288 skip backend api validation
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PreSave/CancellationCalculationsErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PreSave/HandleReasonForCancellationErpOrderCancellationPreSavePlugin.php
Labels: bug, size/s

#289 Chore: erp order cancellation refactoring
  bundles/erp-order-cancellation-api/composer.json
  bundles/erp-order-cancellation-api/src/FondOfImpala/Zed/ErpOrderCancellationApi/Business/Model/ErpOrderCancellationApi.php
  bundles/erp-order-cancellation-mail-connector/composer.json
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorBusinessFactory.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/Model/Mail/MailHandler.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/CancellationManager.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PostSave/RecalculateTotalAmountErpOrderCancellationPostSavePlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PreSave/CancellationCalculationsErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/Transfer/erp_order_cancellation.transfer.xml
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Business/Handler/ErpOrderCancellationItemHandler.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PreSave/HandleReasonForCancellationErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
Labels: enhancement, size/m

#291 feat: change `line_id` type to varchar/string
  bundles/erp-order-cancellation-rest-api/composer.json
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/Transfer/erp_order_cancellation_rest_api.transfer.xml
  bundles/erp-order-cancellation/composer.json
  bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/Transfer/erp_order_cancellation.transfer.xml
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
  dandelion.json
Labels: enhancement, size/s

#292 feat: add `position`, `name`, `unit_price` in response
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/Transfer/erp_order_cancellation_rest_api.transfer.xml
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PreSave/CancellationCalculationsErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/Transfer/erp_order_cancellation.transfer.xml
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
  dandelion.json
Labels: enhancement, size/s

#293 Chore: erp order cancellation rest api unit tests + refactoring
  bundles/erp-order-cancellation-rest-api/config/Shared/config_default.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiBusinessFactory.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PreSave/CancellationCalculationsErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiDependencyProvider.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiEntityManager.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiBusinessFactoryTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiFacadeTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/CancellationManagerTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Expander/ErpOrderCancellationExpanderTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Mapper/RestDataMapperTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Mapper/RestFilterToFilterMapperTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Permission/PermissionCheckerTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Controller/GatewayControllerTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PostSave/RecalculateTotalAmountErpOrderCancellationPostSavePluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellation/PreSave/CancellationCalculationsErpOrderCancellationPreSavePluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/DebitorNumberQueryExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/ExternalReferenceQueryExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/ReferenceQueryExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/RestFilterExpander/DebitorNumberRestFilterToFilterMapperExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/RestFilterExpander/ExternalReferenceRestFilterToFilterMapperExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/RestFilterExpander/ReferenceRestFilterToFilterMapperExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Dependency/Facade/ErpOrderCancellationRestApiToErpOrderCancellationFacadeBridgeTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Dependency/Facade/ErpOrderCancellationRestApiToErpOrderFacadeBridgeTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiDependencyProviderTest.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
  dandelion.json
Labels: enhancement, size/s

#294 chore: add unit tests
  bundles/erp-order-cancellation-mail-connector/composer.json
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/Model/Mail/MailHandler.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorBusinessFactoryTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorFacadeTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/Model/Mail/MailHandlerTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyApprovedErpOrderCancellationPostTransactionPluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyNewErpOrderCancellationPostTransactionPluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyRejectedErpOrderCancellationPostTransactionPluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyApprovedErpOrderCancellationMailTypePluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyReadyErpOrderCancellationMailTypePluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyRejectedErpOrderCancellationMailTypePluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/ErpOrderCancellationMailConnectorDependencyProviderTest.php
  bundles/erp-order-cancellation-rest-api/.github/workflows/main.yml
  bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationCreatePermissionPluginTest.php
  bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationDeletePermissionPluginTest.php
  bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationUpdatePermissionPluginTest.php
  bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/PermissionErpOrderCancellationRestApiDependencyProviderTest.php
  codeception.yml
  dandelion.json
Labels: enhancement, size/s

#295 chore: allow also phpunit/phpunit version >= 10
  bundles/erp-order-cancellation-api/composer.json
  bundles/erp-order-cancellation-api/src/FondOfImpala/Zed/ErpOrderCancellationApi/Business/Model/ErpOrderCancellationApi.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Business/ErpOrderCancellationApiBusinessFactoryTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Business/Model/ErpOrderCancellationApiTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Dependency/Facade/ErpOrderCancellationApiToApiFacadeBridgeTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Dependency/Facade/ErpOrderCancellationApiToErpOrderCancellationFacadeBridgeTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Dependency/QueryContainer/ErpOrderCancellationApiToApiQueryBuilderQueryContainerBridgeTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/ErpOrderCancellationApiDependencyProviderTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorBusinessFactoryTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyApprovedErpOrderCancellationPostTransactionPluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyNewErpOrderCancellationPostTransactionPluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyRejectedErpOrderCancellationPostTransactionPluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyApprovedErpOrderCancellationMailTypePluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyReadyErpOrderCancellationMailTypePluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyRejectedErpOrderCancellationMailTypePluginTest.php
  bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/ErpOrderCancellationMailConnectorDependencyProviderTest.php
  bundles/erp-order-cancellation-rest-api/composer.json
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Expander/ErpOrderCancellationExpanderTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Permission/PermissionCheckerTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/DebitorNumberQueryExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/ExternalReferenceQueryExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/ReferenceQueryExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/RestFilterExpander/DebitorNumberRestFilterToFilterMapperExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/RestFilterExpander/ExternalReferenceRestFilterToFilterMapperExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/RestFilterExpander/ReferenceRestFilterToFilterMapperExpanderPluginTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Dependency/Facade/ErpOrderCancellationRestApiToErpOrderCancellationFacadeBridgeTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Dependency/Facade/ErpOrderCancellationRestApiToErpOrderFacadeBridgeTest.php
  bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiDependencyProviderTest.php
  bundles/erp-order-cancellation/composer.json
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Business/Handler/ErpOrderCancellationItemHandler.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/ErpOrderCancellationBusinessFactoryTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/ErpOrderCancellationFacadeTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Handler/ErpOrderCancellationItemHandlerTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Writer/ErpOrderCancellationItemWriterTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Writer/ErpOrderCancellationWriterTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PostSave/ErpOrderCancellationItemPersistorErpOrderCancellationPostSavePluginTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PreSave/GenerateCancellationReferenceErpOrderCancellationPreSavePluginTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/ErpOrderCancellationDependencyProviderTest.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Shared/PermissionErpOrderCancellationRestApi/Transfer/permission_erp_order_cancellation_rest_api.transfer.xml
  bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationCreatePermissionPluginTest.php
  bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationUpdatePermissionPluginTest.php
  bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/PermissionErpOrderCancellationRestApiDependencyProviderTest.php
Labels: enhancement, size/s

#296 chore: update erp order cancellation bundle github workflows
  bundles/erp-order-cancellation-api/.github/workflows/main.yml
  bundles/erp-order-cancellation-extension/.github/workflows/main.yml
  bundles/erp-order-cancellation-mail-connector/.github/workflows/main.yml
  bundles/erp-order-cancellation-rest-api-extension/.github/workflows/main.yml
  bundles/erp-order-cancellation-rest-api/.github/workflows/main.yml
  bundles/erp-order-cancellation/.github/workflows/main.yml
  bundles/permission-erp-order-cancellation-rest-api/.github/workflows/main.yml
Labels: enhancement, size/s

#297 chore: add missing transfers
  bundles/erp-order-cancellation-extension/src/FondOfImpala/Shared/ErpOrderCancellationExtension/Transfer/erp_order_cancellation_extension.transfer.xml
  bundles/erp-order-cancellation-rest-api-extension/src/FondOfImpala/Shared/ErpOrderCancellationRestApiExtension/Transfer/erp_order_cancellation_rest_api_extension.transfer.xml
Labels: enhancement, size/xs

#299 chore: fix failing standalone ci tasks
  bundles/conditional-availability-company-connector/composer.json
  bundles/conditional-availability-product-page-search/config/Shared/config_default.php
  bundles/conditional-availability/config/Shared/config_default.php
  bundles/document-type-erp-delivery-note/config/Shared/config_default.php
  bundles/document-type-erp-invoice/config/Shared/config_default.php
  bundles/document-type-erp-order/config/Shared/config_default.php
  bundles/jellyfish-sales-order-purchaser/phpstan.neon
  bundles/price-product-price-list/config/Shared/config_default.php
  bundles/price-product-price-list/phpstan.neon
  bundles/product-list-price-product-price-list-page-search/phpstan.neon
Labels: enhancement, size/s
