Repository fond-of-impala/fond-of-impala, pull requests merged in 2024-10, with the labels that each got.

#278 chore: Implement `order cancellation` `Unit Test`
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/ErpOrderCancellationBusinessFactoryTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/ErpOrderCancellationFacadeTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Handler/ErpOrderCancellationItemHandlerTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Reader/ErpOrderCancellationItemReaderTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Reader/ErpOrderCancellationReaderTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Writer/ErpOrderCancellationItemWriterTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Writer/ErpOrderCancellationWriterTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/PluginExecutor/ErpOrderCancellationItemPluginExecutorTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/PluginExecutor/ErpOrderCancellationPluginExecutorTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PostSave/ErpOrderCancellationItemPersistorErpOrderCancellationPostSavePluginTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PreSave/GenerateCancellationReferenceErpOrderCancellationPreSavePluginTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/ErpOrderCancellationConfigTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/ErpOrderCancellationDependencyProviderTest.php
Labels: enhancement

#279 add permission bundle for erp order cancellation and integrate it to rest api bundle
  bundles/erp-order-cancellation-rest-api-extension/src/FondOfImpala/Shared/ErpOrderCancellationRestApiExtension/ErpOrderCancellationRestApiExtensionConstants.php
  bundles/erp-order-cancellation-rest-api-extension/src/FondOfImpala/Shared/ErpOrderCancellationRestApiExtension/Transfer/erp_order_cancellation_rest_api_extension.transfer.xml
  bundles/erp-order-cancellation-rest-api-extension/src/FondOfImpala/Zed/ErpOrderCancellationRestApiExtension/Dependency/Plugin/ErpOrderCancellationPermissionPluginInterface.php
  bundles/erp-order-cancellation-rest-api-extension/src/FondOfImpala/Zed/ErpOrderCancellationRestApiExtension/Dependency/Plugin/ErpOrderCancellationQueryExpanderPluginInterface.php
  bundles/erp-order-cancellation-rest-api/composer.json
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Glue/ErpOrderCancellationRestApi/Processor/Mapper/ErpOrderCancellationMapper.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiConstants.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/Transfer/erp_order_cancellation_rest_api.transfer.xml
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiBusinessFactory.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/CancellationManager.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Mapper/RestFilterToFilterMapper.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Permission/PermissionChecker.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Permission/PermissionCheckerInterface.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/DebitorNumberQueryExpanderPlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/ExternalReferenceQueryExpanderPlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/ReferenceQueryExpanderPlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Dependency/Facade/ErpOrderCancellationRestApiToErpOrderFacadeBridge.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Dependency/Facade/ErpOrderCancellationRestApiToErpOrderFacadeInterface.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiConfig.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiDependencyProvider.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiPersistenceFactory.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiRepository.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiRepositoryInterface.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/Propel/Expander/QueryExpander.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/Propel/Schema/spy_company.schema.xml
  bundles/permission-erp-order-cancellation-rest-api/.github/workflows/main.yml
  bundles/permission-erp-order-cancellation-rest-api/LICENSE
  bundles/permission-erp-order-cancellation-rest-api/Makefile
  bundles/permission-erp-order-cancellation-rest-api/codeception.yml
  bundles/permission-erp-order-cancellation-rest-api/composer.json
  bundles/permission-erp-order-cancellation-rest-api/phpstan.neon
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Shared/PermissionErpOrderCancellationRestApi/PermissionErpOrderCancellationRestApiConstants.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Shared/PermissionErpOrderCancellationRestApi/Transfer/permission_erp_order_cancellation_rest_api.transfer.xml
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationCreatePermissionPlugin.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationDeletePermissionPlugin.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationUpdatePermissionPlugin.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/PermissionReadErpOrderCancellationQueryExpanderPlugin.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/PermissionExtension/ErpOrderCancellationCreatePermissionPlugin.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/PermissionExtension/ErpOrderCancellationManagePermissionPlugin.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/PermissionErpOrderCancellationRestApiConfig.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/PermissionErpOrderCancellationRestApiDependencyProvider.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Persistence/PermissionErpOrderCancellationRestApiPersistenceFactory.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Persistence/PermissionErpOrderCancellationRestApiRepository.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Persistence/PermissionErpOrderCancellationRestApiRepositoryInterface.php
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Persistence/Propel/Schema/spy_company.schema.xml
  bundles/permission-erp-order-cancellation-rest-api/src/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Persistence/Propel/Schema/spy_company_user.schema.xml
  bundles/permission-erp-order-cancellation-rest-api/tests/_bootstrap.php
  bundles/permission-erp-order-cancellation-rest-api/tests/_data/.gitkeep
  bundles/permission-erp-order-cancellation-rest-api/tests/_output/.gitignore
  bundles/permission-erp-order-cancellation-rest-api/tests/_support/.gitkeep
  composer.json
  dandelion.json
Labels: enhancement, size/xl

#280 feat: Implement `erp order cancellation api` `Unit Tests`
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Business/ErpOrderCancellationApiBusinessFactoryTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Business/ErpOrderCancellationApiFacadeTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Business/Model/ErpOrderCancellationApiTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Business/Validator/ErpOrderCancellationApiValidatorTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Communication/Plugin/Api/ErpOrderCancellationApiResourcePluginTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Communication/Plugin/Api/ErpOrderCancellationApiValidatorPluginTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Dependency/Facade/ErpOrderCancellationApiToApiFacadeBridgeTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Dependency/Facade/ErpOrderCancellationApiToErpOrderCancellationFacadeBridgeTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/Dependency/QueryContainer/ErpOrderCancellationApiToApiQueryBuilderQueryContainerBridgeTest.php
  bundles/erp-order-cancellation-api/tests/FondOfImpala/Zed/ErpOrderCancellationApi/ErpOrderCancellationApiDependencyProviderTest.php
Labels: enhancement, size/xs

#281 fix: extend `CompanyCriteriaFilter` with `offset` filter
  bundles/company-type-role/src/FondOfImpala/Shared/CompanyTypeRole/Transfer/company_type_role.transfer.xml
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Business/Synchronizer/CompanyRoleSynchronizer.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Dependency/Facade/CompanyTypeRoleToCompanyFacadeBridge.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Dependency/Facade/CompanyTypeRoleToCompanyFacadeInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepository.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/CompanyTypeRoleRepositoryInterface.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/CompanyMapper.php
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Persistence/Mapper/CompanyMapperInterface.php
  bundles/company-type-role/tests/FondOfImpala/Zed/CompanyTypeRole/Business/Synchronizer/CompanyRoleSynchronizerTest.php
  dandelion.json
Labels: bug, size/m

#282 add erp order cancellation mail connector bundle
  bundles/erp-order-cancellation-extension/src/FondOfImpala/Zed/ErpOrderCancellationExtension/Dependency/Plugin/ErpOrderCancellationPostTransactionPluginInterface.php
  bundles/erp-order-cancellation-mail-connector/.github/workflows/main.yml
  bundles/erp-order-cancellation-mail-connector/LICENSE
  bundles/erp-order-cancellation-mail-connector/Makefile
  bundles/erp-order-cancellation-mail-connector/README.md
  bundles/erp-order-cancellation-mail-connector/codeception.yml
  bundles/erp-order-cancellation-mail-connector/composer.json
  bundles/erp-order-cancellation-mail-connector/phpstan.neon
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Shared/ErpOrderCancellationMailConnector/ErpOrderCancellationMailConnectorConstants.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Shared/ErpOrderCancellationMailConnector/Transfer/erp_order_cancellation_mail_connector.transfer.xml
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorBusinessFactory.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorFacade.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorFacadeInterface.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/Model/Mail/MailHandler.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/Model/Mail/MailHandlerInterface.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyApprovedErpOrderCancellationPostTransactionPlugin.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyNewErpOrderCancellationPostTransactionPlugin.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyRejectedErpOrderCancellationPostTransactionPlugin.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/AbstractErpOrderCancellationMailTypePlugin.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyApprovedErpOrderCancellationMailTypePlugin.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyReadyErpOrderCancellationMailTypePlugin.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyRejectedErpOrderCancellationMailTypePlugin.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Dependency/Facade/ErpOrderCancellationMailConnectorToLocaleFacadeBridge.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Dependency/Facade/ErpOrderCancellationMailConnectorToLocaleFacadeInterface.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Dependency/Facade/ErpOrderCancellationMailConnectorToMailFacadeBridge.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Dependency/Facade/ErpOrderCancellationMailConnectorToMailFacadeInterface.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/ErpOrderCancellationMailConnectorConfig.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/ErpOrderCancellationMailConnectorDependencyProvider.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Persistence/ErpOrderCancellationMailConnectorPersistenceFactory.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Persistence/ErpOrderCancellationMailConnectorRepository.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Persistence/ErpOrderCancellationMailConnectorRepositoryInterface.php
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Persistence/Propel/Schema/spy_company.schema.xml
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Presentation/Mail/notify_erp_order_cancellation.html.twig
  bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Presentation/Mail/notify_erp_order_cancellation.text.twig
  bundles/erp-order-cancellation-mail-connector/tests/_bootstrap.php
  bundles/erp-order-cancellation-mail-connector/tests/_output/.gitignore
  bundles/erp-order-cancellation-mail-connector/tests/_support/.gitkeep
  bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/Transfer/erp_order_cancellation.transfer.xml
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Business/ErpOrderCancellationBusinessFactory.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Writer/ErpOrderCancellationWriter.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Business/PluginExecutor/ErpOrderCancellationPluginExecutor.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Business/PluginExecutor/ErpOrderCancellationPluginExecutorInterface.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PostSave/ErpOrderCancellationItemPersistorErpOrderCancellationPostSavePlugin.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/ErpOrderCancellationDependencyProvider.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/ErpOrderCancellationBusinessFactoryTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/Model/Writer/ErpOrderCancellationWriterTest.php
  bundles/erp-order-cancellation/tests/FondOfImpala/Zed/ErpOrderCancellation/Business/PluginExecutor/ErpOrderCancellationPluginExecutorTest.php
  composer.json
  dandelion.json
Labels: enhancement, size/xl

#283 ad erp order cancellation rest api expander
  bundles/erp-order-cancellation-rest-api-extension/src/FondOfImpala/Zed/ErpOrderCancellationRestApiExtension/Dependency/Plugin/ErpOrderCancellationExpanderPluginInterface.php
  bundles/erp-order-cancellation-rest-api/composer.json
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiConstants.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiBusinessFactory.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Expander/ErpOrderCancellationExpander.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Expander/ErpOrderCancellationExpanderInterface.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Mapper/RestDataMapper.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/Expander/ErpOrderCancellationExternalCustomerExpanderPlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/Expander/ErpOrderCancellationInternalCustomerExpanderPlugin.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiConfig.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/ErpOrderCancellationRestApiDependencyProvider.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiPersistenceFactory.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiRepository.php
  bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Persistence/ErpOrderCancellationRestApiRepositoryInterface.php
  bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/ErpOrderCancellationConstants.php
  bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/Transfer/erp_order_cancellation.transfer.xml
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PreSave/HandleReasonForCancellationErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/ErpOrderCancellationConfig.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
Labels: enhancement, size/m

#284 change reason for cancellation from int to string
  bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/Transfer/erp_order_cancellation.transfer.xml
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Communication/Plugin/PreSave/HandleReasonForCancellationErpOrderCancellationPreSavePlugin.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/ErpOrderCancellationConfig.php
  bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
Labels: enhancement, size/s
