Repository fond-of-impala/fond-of-impala, pull requests merged in 2024-02, with the labels that each got.

#212 chore: add permission for super distribution assignment
  bundles/company-type-role/src/FondOfImpala/Zed/CompanyTypeRole/Communication/Plugin/PermissionExtension/AssignSuperDistributionRolePermissionPlugin.php
  dandelion.json
Labels: enhancement, size/s

#213 fix mapping for multi currency
  bundles/price-list-api/src/FondOfImpala/Zed/PriceListApi/Business/Hydrator/PriceProductsHydrator.php
  dandelion.json
Labels: bug, size/s

#217 fix dandelion.json
  dandelion.json
Labels: bug, size/xs

#219 feat: release `fond-of-impala/order-budgets-bulk-rest-api-extension`
  dandelion.json
Labels: enhancement, size/xs

#220 feat: release `fond-of-impala/order-budgets-bulk-rest-api`
  bundles/order-budgets-bulk-rest-api/composer.json
  dandelion.json
Labels: enhancement, size/xs

#218 fix required dependency
  bundles/conditional-availability-company-search-rest-api/composer.json
Labels: size/xs

#222 fix config naming
  bundles/conditional-availability-company-search-rest-api/src/FondOfImpala/Glue/ConditionalAvailabilityCompanySearchRestApi/Communication/Plugin/CompanySearchRestApi/AvailabilityChannelFallbackRestCompanySearchResultItemExpanderPlugin.php
  bundles/conditional-availability-company-search-rest-api/src/FondOfImpala/Glue/ConditionalAvailabilityCompanySearchRestApi/ConditionalAvailabilityCompanySearchRestApiConfig.php
  bundles/conditional-availability-company-search-rest-api/tests/FondOfImpala/Glue/ConditionalAvailabilityCartConnector/Communication/Plugin/CompanySearchRestApi/AvailabilityChannelFallbackRestCompanySearchResultItemExpanderPluginTest.php
Labels: size/xs

#223 feat: expand company search result with currency
  bundles/currency-company-search-rest-api/.gitignore
  bundles/currency-company-search-rest-api/LICENSE
  bundles/currency-company-search-rest-api/Makefile
  bundles/currency-company-search-rest-api/codeception.yml
  bundles/currency-company-search-rest-api/composer.json
  bundles/currency-company-search-rest-api/phpstan.neon
  bundles/currency-company-search-rest-api/src/FondOfImpala/Glue/CurrencyCompanySearchRestApi/Plugin/CompanySearchRestApiExtension/CurrencyRestCompanySearchResultItemExpanderPlugin.php
  bundles/currency-company-search-rest-api/src/FondOfImpala/Shared/CurrencyCompanySearchRestApi/Transfer/currency_company_search_rest_api.transfer.xml
  bundles/currency-company-search-rest-api/src/FondOfImpala/Zed/CurrencyCompanySearchRestApi/Communication/CurrencyCompanySearchRestApiCommunicationFactory.php
  bundles/currency-company-search-rest-api/src/FondOfImpala/Zed/CurrencyCompanySearchRestApi/Communication/Plugin/CompanySearchRestApiExtension/CurrencyCompanyExpanderPlugin.php
  bundles/currency-company-search-rest-api/src/FondOfImpala/Zed/CurrencyCompanySearchRestApi/CurrencyCompanySearchRestApiDependencyProvider.php
  bundles/currency-company-search-rest-api/src/FondOfImpala/Zed/CurrencyCompanySearchRestApi/Dependency/Facade/CurrencyCompanySearchRestApiToCurrencyFacadeBridge.php
  bundles/currency-company-search-rest-api/src/FondOfImpala/Zed/CurrencyCompanySearchRestApi/Dependency/Facade/CurrencyCompanySearchRestApiToCurrencyFacadeInterface.php
  bundles/currency-company-search-rest-api/tests/FondOfImpala/Glue/CurrencyCompanySearchRestApi/Plugin/CompanySearchRestApiExtension/CurrencyRestCompanySearchResultItemExpanderPluginTest.php
  bundles/currency-company-search-rest-api/tests/FondOfImpala/Zed/CurrencyCompanySearchRestApi/Communication/CurrencyCompanySearchRestApiCommunicationFactoryTest.php
  bundles/currency-company-search-rest-api/tests/FondOfImpala/Zed/CurrencyCompanySearchRestApi/Communication/Plugin/CompanySearchRestApiExtension/CurrencyCompanyExpanderPluginTest.php
  bundles/currency-company-search-rest-api/tests/FondOfImpala/Zed/CurrencyCompanySearchRestApi/Dependency/Facade/CurrencyCompanySearchRestApiToCurrencyFacadeBridgeTest.php
  bundles/currency-company-search-rest-api/tests/_bootstrap.php
  bundles/currency-company-search-rest-api/tests/_data/.gitkeep
  bundles/currency-company-search-rest-api/tests/_output/.gitignore
  bundles/currency-company-search-rest-api/tests/_support/.gitkeep
  codeception.yml
  composer.json
  dandelion.json
Labels: enhancement, size/m

#225 removed grouped image with broken external url from ES data
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductImageGroupPageDataExpander.php
  bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductImageGroupedPageDataExpanderTest.php
  dandelion.json
Labels: enhancement, size/s
