Repository fond-of-impala/fond-of-impala, pull requests merged in 2024-03, with the labels that each got.

#226 fix: add required `composer.json` to `fond-of-impala/product-lists-bulk-rest-api-extension`
  bundles/product-lists-bulk-rest-api-extension/.github/workflows/main.yml
  bundles/product-lists-bulk-rest-api-extension/composer.json
Labels: bug, size/s

#227 fix: add required `product-lists-bulk-rest-api-extension.transfer.xml`
  bundles/product-lists-bulk-rest-api-extension/src/FondOfImpala/Shared/ProductListsBulkRestApiExtension/Transfer/product_lists_bulk_rest_api_extension.transfer.xml
Labels: bug, size/xs

#229 fix: add uuid-behavior to `fond-of-impala/company-product-lists-bulk-rest-api`
  bundles/company-product-lists-bulk-rest-api/composer.json
  bundles/company-product-lists-bulk-rest-api/src/FondOfImpala/Zed/CompanyProductListsBulkRestApi/Persistence/Propel/Schema/spy_company.schema.xml
Labels: bug, size/s

#230 fix: add missing dependency for `fond-of-impala/company-type-product-lists-bulk-rest-api`
  bundles/company-type-product-lists-bulk-rest-api/composer.json
Labels: bug

#232 feat: provide two additional publish methods
  bundles/conditional-availability-page-search/src/FondOfImpala/Client/ConditionalAvailabilityPageSearch/Plugin/SearchExtension/RawConditionalAvailabilityPeriodsResultFormatterPlugin.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacade.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacadeInterface.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchPublisher.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchPublisherInterface.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchClientTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchFactoryTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/Dependency/Client/ConditionalAvailabilityPageSearchToCustomerClientBridgeTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/Dependency/Client/ConditionalAvailabilityPageSearchToSearchClientBridgeTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacadeTest.php
  dandelion.json
Labels: enhancement, size/m

#233 feat: refresh conditional availability periods directly
  bundles/product-list-conditional-availability-page-search/composer.json
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Client/ProductListConditionalAvailabilityPageSearch/Plugin/SearchExtension/ProductListConditionalAvailabilityPageSearchQueryExpanderPlugin.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchExpander.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/ProductListConditionalAvailabilityPageSearchBusinessFactory.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/Reader/ProductListReader.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/Reader/ProductListReaderInterface.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/Plugin/Event/Listener/ProductListProductConcreteListener.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/ProductListConditionalAvailabilityPageSearchCommunicationFactory.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToConditionalAvailabilityPageSearchFacadeBridge.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToConditionalAvailabilityPageSearchFacadeInterface.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToEventBehaviorFacadeBridge.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToEventBehaviorFacadeInterface.php
  bundles/product-list-conditional-availability-page-search/src/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/ProductListConditionalAvailabilityPageSearchDependencyProvider.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Client/ProductListConditionalAvailabilityPageSearch/Dependency/Client/ProductListConditionalAvailabilityPageSearchToCustomerClientBridgeTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Client/ProductListConditionalAvailabilityPageSearch/Plugin/SearchExtension/ProductListConditionalAvailabilityPageSearchQueryExpanderPluginTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Client/ProductListConditionalAvailabilityPageSearch/ProductListConditionalAvailabilityPageSearchDependencyProviderTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Client/ProductListConditionalAvailabilityPageSearch/ProductListConditionalAvailabilityPageSearchFactoryTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchExpanderTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/ProductListConditionalAvailabilityPageSearchBusinessFactoryTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/ProductListConditionalAvailabilityPageSearchFacadeTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Business/Reader/ProductListReaderTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/ConditionalAvailabilityPageSearchExtension/ProductListConditionalAvailabilityPeriodPageDataExpanderPluginTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/ConditionalAvailabilityPageSearchExtension/ProductListConditionalAvailabilityPeriodPageSearchDataExpanderPluginTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/Plugin/Event/Subscriber/ProductListConditionalAvailabilityPageSearchEventSubscriberTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Communication/ProductListConditionalAvailabilityPageSearchCommunicationFactoryTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToConditionalAvailabilityFacadeBridgeTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToConditionalAvailabilityPageSearchFacadeBridgeTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToEventBehaviorFacadeBridgeTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/Dependency/Facade/ProductListConditionalAvailabilityPageSearchToProductListFacadeBridgeTest.php
  bundles/product-list-conditional-availability-page-search/tests/FondOfImpala/Zed/ProductListConditionalAvailabilityPageSearch/ProductListConditionalAvailabilityPageSearchDependencyProviderTest.php
  dandelion.json
Labels: size/m

#234 product price search company currency
  bundles/price-product-price-list-search-rest-api-extension/.github/workflows/main.yml
  bundles/price-product-price-list-search-rest-api-extension/.gitignore
  bundles/price-product-price-list-search-rest-api-extension/LICENSE
  bundles/price-product-price-list-search-rest-api-extension/Makefile
  bundles/price-product-price-list-search-rest-api-extension/README.md
  bundles/price-product-price-list-search-rest-api-extension/codeception.yml
  bundles/price-product-price-list-search-rest-api-extension/composer.json
  bundles/price-product-price-list-search-rest-api-extension/phpstan.neon
  bundles/price-product-price-list-search-rest-api-extension/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiExtension/Plugin/ReducerPluginInterface.php
  bundles/price-product-price-list-search-rest-api-extension/tests/_bootstrap.php
  bundles/price-product-price-list-search-rest-api-extension/tests/_data/.gitkeep
  bundles/price-product-price-list-search-rest-api-extension/tests/_output/.gitignore
  bundles/price-product-price-list-search-rest-api-extension/tests/_support/.gitkeep
  composer.json
  dandelion.json
Labels: enhancement, size/m

#236 price data reduce executor
  bundles/price-product-price-list-search-rest-api/composer.json
  bundles/price-product-price-list-search-rest-api/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/PriceProductPriceListSearchRestApiDependencyProvider.php
  bundles/price-product-price-list-search-rest-api/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/PriceProductPriceListSearchRestApiFactory.php
  bundles/price-product-price-list-search-rest-api/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/Processor/PriceProductPriceListSearch/AbstractPriceProductPriceListSearchReader.php
  bundles/price-product-price-list-search-rest-api/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/Processor/PriceProductPriceListSearch/PriceProductAbstractPriceListSearchReader.php
  bundles/price-product-price-list-search-rest-api/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/Processor/PriceProductPriceListSearch/PriceProductConcretePriceListSearchReader.php
  bundles/price-product-price-list-search-rest-api/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/Processor/Reducer/PriceDataReducerPluginExecutor.php
  bundles/price-product-price-list-search-rest-api/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/Processor/Reducer/PriceDataReducerPluginExecutorInterface.php
  bundles/price-product-price-list-search-rest-api/tests/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/PriceProductPriceListSearchRestApiFactoryTest.php
  bundles/price-product-price-list-search-rest-api/tests/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/Processor/PriceProductPriceListSearch/PriceProductAbstractPriceListSearchReaderTest.php
  bundles/price-product-price-list-search-rest-api/tests/FondOfImpala/Glue/PriceProductPriceListSearchRestApi/Processor/PriceProductPriceListSearch/PriceProductConcretePriceListSearchReaderTest.php
  dandelion.json
Labels: enhancement, size/m

#235 company currency connector
  bundles/price-product-price-list-search-rest-api-company-currency-connector/.gitignore
  bundles/price-product-price-list-search-rest-api-company-currency-connector/LICENSE
  bundles/price-product-price-list-search-rest-api-company-currency-connector/Makefile
  bundles/price-product-price-list-search-rest-api-company-currency-connector/README.md
  bundles/price-product-price-list-search-rest-api-company-currency-connector/codeception.yml
  bundles/price-product-price-list-search-rest-api-company-currency-connector/composer.json
  bundles/price-product-price-list-search-rest-api-company-currency-connector/phpstan.neon
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Dependency/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorToZedRequestClientBridge.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Dependency/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorToZedRequestClientInterface.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorClient.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorClientInterface.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorDependencyProvider.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorFactory.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorStub.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorStubInterface.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Dependency/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorToCustomerClientBridge.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Dependency/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorToCustomerClientInterface.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Plugin/PriceProductPriceListSearchRestApi/AbstractPriceListToCompanyCurrencyReducerPlugin.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Plugin/PriceProductPriceListSearchRestApi/ProductAbstractPriceListToCompanyCurrencyReducerPlugin.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Plugin/PriceProductPriceListSearchRestApi/ProductConcretePriceListToCompanyCurrencyReducerPlugin.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorDependencyProvider.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorFactory.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Shared/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Transfer/price_product_price_list_search_rest_api_company_currency_connector.transfer.xml
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Communication/Controller/GatewayController.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Communication/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorCommunicationFactory.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Dependency/Facade/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorToCurrencyFacadeBridge.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Dependency/Facade/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorToCurrencyFacadeInterface.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/src/FondOfImpala/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorDependencyProvider.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Dependency/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorToZedRequestClientBridgeTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorClientTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorDependencyProviderTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorFactoryTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Client/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorStubTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Plugin/PriceProductPriceListSearchRestApi/ProductAbstractPriceListToCompanyReducerPluginTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Plugin/PriceProductPriceListSearchRestApi/ProductConcretePriceListToCompanyReducerPluginTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Glue/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/PriceProductPriceListSearchRestApiCompanyCurrencyConnectorDependencyProviderTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/FondOfImpala/Zed/PriceProductPriceListSearchRestApiCompanyCurrencyConnector/Communication/Controller/GatewayControllerTest.php
  bundles/price-product-price-list-search-rest-api-company-currency-connector/tests/_bootstrap.php
  composer.json
  dandelion.json
Labels: enhancement, size/l

#237 add ci stuff
  bundles/price-product-price-list-search-rest-api-company-currency-connector/.github/workflows/main.yml
  codeception.yml
Labels: size/s

#231 create quote with company currency
  bundles/company-user-carts-rest-api-extension/.github/workflows/main.yml
  bundles/company-user-carts-rest-api-extension/.gitignore
  bundles/company-user-carts-rest-api-extension/LICENSE
  bundles/company-user-carts-rest-api-extension/Makefile
  bundles/company-user-carts-rest-api-extension/codeception.yml
  bundles/company-user-carts-rest-api-extension/composer.json
  bundles/company-user-carts-rest-api-extension/phpstan.neon
  bundles/company-user-carts-rest-api-extension/src/FondOfImpala/Zed/CompanyUserCartsRestApiExtension/Dependency/Plugin/QuoteCreateExpanderPluginInterface.php
  bundles/company-user-carts-rest-api-extension/tests/_bootstrap.php
  bundles/company-user-carts-rest-api-extension/tests/_data/.gitkeep
  bundles/company-user-carts-rest-api-extension/tests/_output/.gitignore
  bundles/company-user-carts-rest-api-extension/tests/_support/.gitkeep
  bundles/company-user-carts-rest-api/src/FondOfImpala/Shared/CompanyUserCartsRestApi/CompanyUserCartsRestApiConstants.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Business/CompanyUserCartsRestApiBusinessFactory.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Business/Creator/QuoteCreator.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Business/Expander/QuoteCreateExpander.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Business/Expander/QuoteCreateExpanderInterface.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Communication/CompanyUserCartsRestApiCommunicationFactory.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Communication/Plugin/CompanyCurrencyToQuoteExpanderPlugin.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/CompanyUserCartsRestApiDependencyProvider.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Dependency/Facade/CompanyUserCartsRestApiToCurrencyFacadeBridge.php
  bundles/company-user-carts-rest-api/src/FondOfImpala/Zed/CompanyUserCartsRestApi/Dependency/Facade/CompanyUserCartsRestApiToCurrencyFacadeInterface.php
  bundles/company-user-carts-rest-api/tests/FondOfImpala/Zed/CompanyUserCartsRestApi/Business/CompanyUserCartsRestApiBusinessFactoryTest.php
  bundles/company-user-carts-rest-api/tests/FondOfImpala/Zed/CompanyUserCartsRestApi/Business/Creator/QuoteCreatorTest.php
  composer.json
  dandelion.json
Labels: enhancement, size/l

#241 feat: configurable chunk size for conditional availability events
  bundles/business-central-product-lists-bulk-rest-api/tests/FondOfImpala/Glue/BusinessCentralProductListsBulkRestApi/Plugin/ProductListsBulkRestApiExtension/BusinessCentralRestProductListsBulkRequestAssignmentMapperPluginTest.php
  bundles/company-product-lists-bulk-rest-api/tests/FondOfImpala/Glue/CompanyProductListsBulkRestApi/Plugin/ProductListsBulkRestApiExtension/CompanyRestProductListsBulkRequestAssignmentMapperPluginTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Model/ConditionalAvailabilityEnsureEarliestDateTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/ConditionalAvailabilityReaderTest.php
  bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/CustomerReaderTest.php
  bundles/conditional-availability-checkout-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCheckoutConnector/Communication/Plugin/CheckoutExtension/ConditionalAvailabilityCheckoutPreConditionPluginTest.php
  bundles/conditional-availability-page-search/composer.json
  bundles/conditional-availability-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchConstants.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/ConditionalAvailabilityPageSearchCommunicationFactory.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Queue/ConditionalAvailabilityQueueMessageProcessorPlugin.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Queue/ConditionalAvailabilityRetryQueueMessageProcessorPlugin.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchConfig.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchDependencyProvider.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToEventFacadeBridge.php
  bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToEventFacadeInterface.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/ConditionalAvailabilityPageSearchCommunicationFactoryTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Queue/ConditionalAvailabilityQueueMessageProcessorPluginTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/Queue/ConditionalAvailabilityRetryQueueMessageProcessorPluginTest.php
  bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Dependency/Facade/ConditionalAvailabilityPageSearchToEventFacadeBridgeTest.php
  bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/Model/ConditionalAvailabilityWriterTest.php
  bundles/customer-anonymizer-company-user-connector/tests/FondOfImpala/Zed/CustomerAnonymizerCompanyUserConnector/Business/Deleter/CompanyUserDeleterTest.php
  bundles/customer-product-lists-bulk-rest-api/tests/FondOfImpala/Glue/CustomerProductListsBulkRestApi/Plugin/ProductListsBulkRestApiExtension/CustomerRestProductListsBulkRequestAssignmentMapperPluginTest.php
  bundles/order-budgets-bulk-rest-api/tests/FondOfImpala/Glue/OrderBudgetsBulkRestApi/Processor/Builder/RestResponseBuilderTest.php
  bundles/order-budgets-bulk-rest-api/tests/FondOfImpala/Glue/OrderBudgetsBulkRestApi/Processor/Mapper/RestOrderBudgetsBulkRequestOrderBudgetMapperTest.php
  bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductImageGroupedPageDataExpanderTest.php
  bundles/product-lists-bulk-rest-api/tests/FondOfImpala/Glue/ProductListsBulkRestApi/Processor/Builder/RestResponseBuilderTest.php
  bundles/product-lists-bulk-rest-api/tests/FondOfImpala/Glue/ProductListsBulkRestApi/Processor/Mapper/RestProductListsBulkRequestAssignmentMapperTest.php
  composer.json
  dandelion.json
Labels: enhancement, size/m

#242 feat: initialize `enhanced-catalog-extension`-bundle
  bundles/enhanced-catalog-extension/.github/workflows/main.yml
  bundles/enhanced-catalog-extension/.gitignore
  bundles/enhanced-catalog-extension/LICENSE
  bundles/enhanced-catalog-extension/Makefile
  bundles/enhanced-catalog-extension/codeception.yml
  bundles/enhanced-catalog-extension/composer.json
  bundles/enhanced-catalog-extension/phpstan.neon
  bundles/enhanced-catalog-extension/src/FondOfImpala/Client/EnhancedCatalogExtension/Dependency/Plugin/ProductExpanderPluginInterface.php
  bundles/enhanced-catalog-extension/tests/_bootstrap.php
  bundles/enhanced-catalog-extension/tests/_data/.gitkeep
  bundles/enhanced-catalog-extension/tests/_output/.gitignore
  bundles/enhanced-catalog-extension/tests/_support/.gitkeep
  composer.json
  dandelion.json
Labels: enhancement, size/m

#243 feat: initialize `enhanced-catalog`-bundle
  bundles/enhanced-catalog/.gitignore
  bundles/enhanced-catalog/LICENSE
  bundles/enhanced-catalog/Makefile
  bundles/enhanced-catalog/codeception.yml
  bundles/enhanced-catalog/composer.json
  bundles/enhanced-catalog/phpstan.neon
  bundles/enhanced-catalog/src/FondOfImpala/Client/EnhancedCatalog/EnhancedCatalogDependencyProvider.php
  bundles/enhanced-catalog/src/FondOfImpala/Client/EnhancedCatalog/EnhancedCatalogFactory.php
  bundles/enhanced-catalog/src/FondOfImpala/Client/EnhancedCatalog/Formatter/RawCatalogSearchResultFormatter.php
  bundles/enhanced-catalog/src/FondOfImpala/Client/EnhancedCatalog/Formatter/RawCatalogSearchResultFormatterInterface.php
  bundles/enhanced-catalog/src/FondOfImpala/Client/EnhancedCatalog/Plugin/ResultFormatter/RawCatalogSearchResultFormatterPlugin.php
  bundles/enhanced-catalog/tests/FondOfImpala/Client/EnhancedCatalog/EnhancedCatalogFactoryTest.php
  bundles/enhanced-catalog/tests/FondOfImpala/Client/EnhancedCatalog/Formatter/RawCatalogSearchResultFormatterTest.php
  bundles/enhanced-catalog/tests/FondOfImpala/Client/EnhancedCatalog/Plugin/ResultFormatter/RawCatalogSearchResultFormatterPluginTest.php
  bundles/enhanced-catalog/tests/_bootstrap.php
  bundles/enhanced-catalog/tests/_data/.gitkeep
  bundles/enhanced-catalog/tests/_output/.gitignore
  bundles/enhanced-catalog/tests/_support/.gitkeep
  codeception.yml
  composer.json
  dandelion.json
Labels: enhancement, size/m

#246 fix: remove typo from required dependency
  bundles/product-image-grouping-product-page-search/composer.json
Labels: bug, size/xs

#247 chore: add ci workflow to `enhanced-catalog`-bundle
  bundles/enhanced-catalog/.github/workflows/main.yml
Labels: enhancement, size/s

#245 feat: initialize `product-group-hash`-bundle
  bundles/product-group-hash/.github/workflows/main.yml
  bundles/product-group-hash/.gitignore
  bundles/product-group-hash/LICENSE
  bundles/product-group-hash/Makefile
  bundles/product-group-hash/codeception.yml
  bundles/product-group-hash/composer.json
  bundles/product-group-hash/phpstan.neon
  bundles/product-group-hash/src/FondOfImpala/Client/ProductGroupHash/Plugin/EnhancedCatalogExtension/GroupCountProductExpanderPlugin.php
  bundles/product-group-hash/src/FondOfImpala/Client/ProductGroupHash/Plugin/SearchExtension/GroupHashQueryExpanderPlugin.php
  bundles/product-group-hash/src/FondOfImpala/Client/ProductGroupHash/Plugin/SearchExtension/OnePerGroupHashQueryExpanderPlugin.php
  bundles/product-group-hash/src/FondOfImpala/Shared/ProductGroupHash/ProductGroupHashConstants.php
  bundles/product-group-hash/src/FondOfImpala/Shared/ProductGroupHash/Schema/page.json
  bundles/product-group-hash/src/FondOfImpala/Shared/ProductGroupHash/Transfer/product_group_hash.transfer.xml
  bundles/product-group-hash/src/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Listener/ProductGroupHashListener.php
  bundles/product-group-hash/src/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Subscriber/ProductGroupHashEventSubscriber.php
  bundles/product-group-hash/src/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/ProductPageSearchExtension/GroupHashProductAbstractMapExpanderPlugin.php
  bundles/product-group-hash/src/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/ProductPageSearchExtension/GroupHashProductPageDataExpanderPlugin.php
  bundles/product-group-hash/src/FondOfImpala/Zed/ProductGroupHash/Persistence/Propel/Schema/spy_product.schema.xml
  bundles/product-group-hash/tests/FondOfImpala/Client/ProductGroupHash/Plugin/EnhancedCatalogExtension/GroupCountProductExpanderPluginTest.php
  bundles/product-group-hash/tests/FondOfImpala/Client/ProductGroupHash/Plugin/SearchExtension/GroupHashQueryExpanderPluginTest.php
  bundles/product-group-hash/tests/FondOfImpala/Client/ProductGroupHash/Plugin/SearchExtension/OnePerGroupHashQueryExpanderPluginTest.php
  bundles/product-group-hash/tests/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Listener/ProductGroupHashListenerTest.php
  bundles/product-group-hash/tests/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Subscriber/ProductGroupHashEventSubscriberTest.php
  bundles/product-group-hash/tests/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/ProductPageSearchExtension/GroupHashProductAbstractMapExpanderPluginTest.php
  bundles/product-group-hash/tests/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/ProductPageSearchExtension/GroupHashProductPageDataExpanderPluginTest.php
  bundles/product-group-hash/tests/_bootstrap.php
  bundles/product-group-hash/tests/_data/.gitkeep
  bundles/product-group-hash/tests/_output/.gitignore
  bundles/product-group-hash/tests/_support/.gitkeep
  codeception.yml
  composer.json
  dandelion.json
Labels: enhancement, size/l

#248 fix: replace duplicated event name in subscriber
  bundles/product-group-hash/src/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Subscriber/ProductGroupHashEventSubscriber.php
  bundles/product-group-hash/tests/FondOfImpala/Zed/ProductGroupHash/Communication/Plugin/Event/Subscriber/ProductGroupHashEventSubscriberTest.php
Labels: bug, size/xs
