Repository fond-of-impala/fond-of-impala, pull requests merged in 2024-01, with the labels that each got.

#180 🧹 add cleanup command for cleaning up bundle data
  Makefile
Labels: enhancement, size/xs

#191 🧹 use fond-of-impala/navision-company
  bundles/company-users-bulk-rest-api-business-central-connector/composer.json
  composer.json
  dandelion.json
Labels: enhancement, size/xs

#192 🧹 fix facade naming from ...ByUuid to ...ByExternalReference
  bundles/navision-company-business-unit/src/FondOfImpala/Zed/NavisionCompanyBusinessUnit/Business/NavisionCompanyBusinessUnitFacade.php
  bundles/navision-company-business-unit/src/FondOfImpala/Zed/NavisionCompanyBusinessUnit/Business/NavisionCompanyBusinessUnitFacadeInterface.php
  bundles/navision-company-business-unit/tests/FondOfImpala/Zed/NavisionCompanyBusinessUnit/Business/NavisionCompanyBusinessUnitFacadeTest.php
Labels: enhancement, size/xs

#197 ✨ Add facade method for finding `ConditionalAvailabilities` by `ProductAbstractIds`
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacade.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacadeInterface.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepository.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepositoryInterface.php
  bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacadeTest.php
  dandelion.json
Labels: enhancement

#199 ✨ Increase performance of `ProductPageLoadExpander`
  bundles/conditional-availability-product-page-search/composer.json
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactory.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductPageLoadExpander.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToConditionalAvailabilityFacadeBridge.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToConditionalAvailabilityFacadeInterface.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToProductFacadeBridge.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToProductFacadeInterface.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactoryTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductPageLoadExpanderTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToConditionalAvailabilityFacadeBridgeTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToProductFacadeBridgeTest.php
  dandelion.json
Labels: enhancement, size/m

#200 🧹 Use correct dependencies in split repos
  bundles/collaborative-cart-search-rest-api/composer.json
  dandelion.json
Labels: enhancement, size/xs

#201 fix typo in conditional-availability-cart-connector
  bundles/collaborative-cart-search-rest-api/.github/workflows/main.yml
  bundles/conditional-availability-cart-connector/composer.json
Labels: bug, size/s

#205 🧹 fix standalone ci company business units carts rest api
  bundles/company-business-units-carts-rest-api/composer.json
  bundles/company-business-units-carts-rest-api/src/FondOfImpala/Shared/CompanyBusinessUnitsCartsRestApi/Transfer/company_business_units_carts_rest_api.transfer.xml
  bundles/company-business-units-carts-rest-api/tests/FondOfImpala/Glue/CompanyBusinessUnitsCartsRestApi/Processor/Mapper/CartItemMapperTest.php
Labels: enhancement, size/s

#203 ✨ Add facade method for finding `GroupedConditionalAvailabilities` by `ProductAbstractIds`
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacade.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacadeInterface.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepository.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepositoryInterface.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/Propel/Mapper/ConditionalAvailabilityMapper.php
  bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/Propel/Mapper/ConditionalAvailabilityMapperInterface.php
  bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacadeTest.php
  dandelion.json
Labels: enhancement, size/m

#204 ✨ Reduce sub queries in `ProductPageLoadExpander`
  bundles/conditional-availability-product-page-search/composer.json
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductPageLoadExpander.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToConditionalAvailabilityFacadeBridge.php
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToConditionalAvailabilityFacadeInterface.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductPageLoadExpanderTest.php
  bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Dependency/Facade/ConditionalAvailabilityProductPageSearchToConditionalAvailabilityFacadeBridgeTest.php
  dandelion.json
Labels: enhancement, size/s

#207 🐛 Move select select to main query
  bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Persistence/ConditionalAvailabilityProductPageSearchRepository.php
Labels: bug, size/xs

#210 ✨ product image group url validation
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductImageGroupPageDataExpander.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductPageDataExpanderInterface.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/ProductImageGroupingProductPageSearchBusinessFactory.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/ProductImageGroupingProductPageSearchFacade.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/ProductImageGroupingProductPageSearchFacadeInterface.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Validator/UrlValidator.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Validator/UrlValidatorInterface.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupMapExpanderPlugin.php
  bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPlugin.php
  bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductImageGroupedPageDataExpanderTest.php
  bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Validator/UrlValidatorTest.php
  bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPluginTest.php
  dandelion.json
Labels: enhancement, size/m
